// Datos mock para categorías
export const mockCategoriesData = {
  categories: [
    {
      id: 'celulares',
      name: 'Celulares',
      image: '/images/categories/celulares.png',
      isMain: false,
      slug: 'celulares',
      description: 'Los últimos modelos de las mejores marcas',
    },
    {
      id: 'auriculares',
      name: 'Auriculares',
      image: '/images/categories/auriculares.png',
      isMain: false,
      slug: 'auriculares',
      description: 'Sonido de alta fidelidad y cancelación de ruido',
    },
    {
      id: 'parlantes',
      name: 'Parlantes',
      image: '/images/categories/parlantes.png',
      isMain: false,
      slug: 'parlantes',
      description: 'Potencia y claridad en cada nota',
    },
    {
      id: 'apple',
      name: 'Apple',
      image: '/images/categories/apple.png',
      isMain: false,
      slug: 'apple',
      description: 'El ecosistema completo de Apple en tus manos',
    },
    {
      id: 'notebooks',
      name: 'Notebooks',
      image: '/images/categories/notebooks.png',
      isMain: false,
      slug: 'notebooks',
      description: 'Potencia portátil para trabajo y diseño',
    },
    {
      id: 'iphone',
      name: 'iPhone',
      image: '/images/categories/iphone.png',
      isMain: false,
      slug: 'iphone',
      description: 'El teléfono más avanzado con el chip más potente',
    },
    {
      id: 'macbook',
      name: 'Macbook',
      image: '/images/categories/macbook.png',
      isMain: false,
      slug: 'macbook',
      description: 'Rendimiento excepcional para profesionales',
    },
    {
      id: 'watch',
      name: 'Apple Watch',
      image: '/images/categories/watch.png',
      isMain: false,
      slug: 'watch',
      description: 'Lleva tu salud y conectividad en tu muñeca',
    },
  ],
};
