// Datos mock para simular base de datos
export const mockProductsData = {
    bombas: [
        {
            id: '1',
            name: 'Auriculares Gaming RGB',
            brand: 'JBL',
            sku: '51307',
            price: 344279,
            discountPercentage: 15,
            description: 'Auriculares gaming premium con RGB',
            imageUrls: ['/images/JBLBoombox3Lifestyle01904x560px-(5014).webp'],
            category: 'Audio',
            discountBase: true,
        },
        {
            id: '2',
            name: 'Productos Apple',
            brand: 'Apple',
            sku: '59161',
            price: 2466729,
            discountPercentage: 12,
            description: 'Accesorios y productos Apple premium',
            imageUrls: ['/images/productos-apple.webp'],
            category: 'Electrónica',
            discountBase: true,
        },
        {
            id: '3',
            name: 'Realme 14T',
            brand: 'Realme',
            sku: '48119',
            price: 423189,
            discountPercentage: 18,
            description: 'Smartphone Realme de última generación',
            imageUrls: ['/images/xiaomi-14t.webp'],
            category: 'Celulares',
            discountBase: true,
        },
        {
            id: '4',
            name: 'Portátil JBL',
            brand: 'JBL',
            sku: '48117',
            price: 166969,
            discountPercentage: 20,
            description: 'Altavoz portátil JBL de alta calidad',
            imageUrls: ['/images/JBLPortableAudioLifestyleGroupImage1.webp'],
            category: 'Audio',
            discountBase: true,
        },
        {
            id: '5',
            name: 'MacBook Air',
            brand: 'Apple',
            sku: '62018',
            price: 328639,
            discountPercentage: 10,
            description: 'Laptop ultraligera y potente',
            imageUrls: ['/images/MacBookAirM410.webp'],
            category: 'Computadoras',
            discountBase: true,
        },
        {
            id: '6',
            name: 'Tecnología Premiumasdasd',
            brand: 'JB Imports',
            sku: '39968',
            price: 1220999,
            discountPercentage: 25,
            description: 'Paquete premium de tecnología',
            imageUrls: ['/images/DC_20260306150520_9z1vjiMY.jpg'],
            category: 'Paquetes',
            discountBase: true,
        },
        {
            id: '12',
            name: 'Tecnología Trucha',
            brand: 'JB Imports',
            sku: '39968',
            price: 1220999,
            discountPercentage: 25,
            description: 'Paquete premium de tecnología',
            imageUrls: ['/images/DC_20260306150520_9z1vjiMY.jpg'],
            category: 'Paquetes',
            discountBase: true,
        },
    ],
    nuevas: [
        {
            id: '7',
            name: 'Laptop Gaming MacBook',
            brand: 'Apple',
            sku: '71204',
            price: 3899999,
            discountPercentage: 8,
            description: 'MacBook de última generación para gaming',
            imageUrls: ['/images/MacBookAirM410.webp'],
            category: 'Computadoras',
            discountBase: false,
        },
        {
            id: '8',
            name: 'Productos Apple',
            brand: 'Apple',
            sku: '44782',
            price: 899999,
            discountPercentage: 14,
            description: 'Nuevos productos del ecosistema Apple',
            imageUrls: ['/images/productos-apple.webp'],
            category: 'Electrónica',
            discountBase: false,
        },
        {
            id: '9',
            name: 'Audio JBL Premium',
            brand: 'JBL',
            sku: '55291',
            price: 1299999,
            discountPercentage: 21,
            description: 'Sistema de audio JBL de alta fidelidad',
            imageUrls: ['/images/JBLBoombox3Lifestyle01904x560px-(5014).webp'],
            category: 'Audio',
            discountBase: false,
        },
        {
            id: '10',
            name: 'Audio Portátil JBL',
            brand: 'JBL',
            sku: '38421',
            price: 2199999,
            discountPercentage: 11,
            description: 'Altavoz portátil JBL profesional',
            imageUrls: ['/images/JBLPortableAudioLifestyleGroupImage1.webp'],
            category: 'Audio',
            discountBase: false,
        },
        {
            id: '11',
            name: 'Realme Tech 14T',
            brand: 'Realme',
            sku: '29746',
            price: 999999,
            discountPercentage: 9,
            description: 'Smartphone Realme con especificaciones premium',
            imageUrls: ['/images/xiaomi-14t.webp'],
            category: 'Celulares',
            discountBase: false,
        },
        {
            id: '12',
            name: 'Tech Premium JB',
            brand: 'JB Imports',
            sku: '67853',
            price: 699999,
            discountPercentage: 16,
            description: 'Bundle exclusivo de tecnología',
            imageUrls: ['/images/DC_20260306150520_9z1vjiMY.jpg'],
            category: 'Paquetes',
            discountBase: false,
        },
    ],
};
