// Datos mock para categorías
export const mockCategoriesData = {
  categories: [
    {
      id: 'pc-escritorio',
      name: 'PC de Escritorio',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Principal_20_6f1017ee-45aa-43b8-a9b1-2e5943bb0101.jpg',
      isMain: true,
      slug: 'pc-escritorio',
      description: 'Computadoras de escritorio de alta performance',
    },
    {
      id: 'placas-video',
      name: 'Placas de Video',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_8_7bb94f0e-d382-484b-b051-729e5b43d592.jpg',
      isMain: false,
      slug: 'placas-video',
      description: 'Tarjetas gráficas para gaming y profesionales',
    },
    {
      id: 'monitores',
      name: 'Monitores',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_14_810a81ed-1cf1-4918-9614-65d749e49b13.jpg',
      isMain: false,
      slug: 'monitores',
      description: 'Pantallas FHD, 144Hz y 4K',
    },
    {
      id: 'notebooks',
      name: 'Notebooks',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_11_71faed0f-83e6-436d-9854-70d0ab4771c9.jpg',
      isMain: false,
      slug: 'notebooks',
      description: 'Laptops para trabajo y gaming',
    },
    {
      id: 'memorias-ram',
      name: 'Memorias RAM',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_5_ac448f96-41c9-4320-a874-a4264f4e95cd.jpg',
      isMain: false,
      slug: 'memorias-ram',
      description: 'Memoria RAM DDR4 y DDR5',
    },
    {
      id: 'mothers',
      name: 'Mothers',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_6_9e4e3baa-a228-4245-8578-e1ffba7fc38c.jpg',
      isMain: false,
      slug: 'mothers',
      description: 'Placas madre para todas las plataformas',
    },
    {
      id: 'gabinetes',
      name: 'Gabinetes',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_18_99233303-1c1a-4e6b-8c6a-0c3a586ca7f2.jpg',
      isMain: false,
      slug: 'gabinetes',
      description: 'Gabinetes ATX, Micro ATX y Mini ITX',
    },
    {
      id: 'fuentes',
      name: 'Fuentes',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_9_5c571df2-0c28-435c-9eee-8e086f7eeceb.jpg',
      isMain: false,
      slug: 'fuentes',
      description: 'Fuentes de poder certificadas',
    },
    {
      id: 'perifericos',
      name: 'Periféricos',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_1_424beac4-2f69-47f2-ae9a-eae752fef9f3.jpg',
      isMain: false,
      slug: 'perifericos',
      description: 'Teclados, ratones y headsets gaming',
    },
    {
      id: 'almacenamiento',
      name: 'Almacenamiento',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_3_796a727e-6684-4cd8-a9ac-16e59f70efff.jpg',
      isMain: false,
      slug: 'almacenamiento',
      description: 'SSDs NVMe, SATA y discos duros',
    },
    {
      id: 'impresoras',
      name: 'Impresoras e Insumos',
      image: 'https://imagenes.compragamer.com/home_carrusel_agrupadores/Secundaria_19_f1f55f63-89d7-441b-95fa-c03064e5e9cf.jpg',
      isMain: false,
      slug: 'impresoras',
      description: 'Impresoras y consumibles',
    },
  ],
};
