/**
 * Especificaciones técnicas individuales de cada producto.
 * Cada clave es el ID del producto (debe coincidir con los IDs en mockCategoryProducts.ts).
 * Para agregar o editar especificaciones de un producto, buscá su ID y modificá el array.
 */

export interface Spec {
  label: string;
  value: string;
}

export const productSpecifications: Record<string, Spec[]> = {
  // ─────────────────────────────────────────
  // PC ESCRITORIO
  // ─────────────────────────────────────────
  'pc-1': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'PC Gamer RTX5080 V70' },
    { label: 'Procesador', value: 'AMD Ryzen 7 9800X3D' },
    { label: 'Tarjeta de video', value: 'NVIDIA GeForce RTX 5080' },
    { label: 'RAM', value: '32GB DDR5 6000MHz' },
    { label: 'Almacenamiento', value: '2TB NVMe Gen 5' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-2': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'Workstation Ryzen 9 5950X' },
    { label: 'Procesador', value: 'AMD Ryzen 9 5950X' },
    { label: 'RAM', value: '64GB DDR4 3600MHz ECC' },
    { label: 'Almacenamiento', value: '4TB NVMe + 8TB HDD' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-3': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'PC Gaming i5 RTX 3060' },
    { label: 'Procesador', value: 'Intel Core i5-13600KF' },
    { label: 'Tarjeta de video', value: 'NVIDIA GeForce RTX 3060' },
    { label: 'RAM', value: '16GB DDR4 3200MHz' },
    { label: 'Almacenamiento', value: '1TB NVMe' },
    { label: 'Sistema operativo', value: 'Windows 11 Home' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-4': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'Pro Design RTX 4090' },
    { label: 'Procesador', value: 'Intel Core i9-14900K' },
    { label: 'Tarjeta de video', value: 'NVIDIA GeForce RTX 4090' },
    { label: 'RAM', value: '64GB DDR5 5600MHz' },
    { label: 'Almacenamiento', value: '4TB NVMe Gen 4' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-5': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'Streaming i9 32GB' },
    { label: 'Procesador', value: 'Intel Core i9-13900K' },
    { label: 'RAM', value: '32GB DDR5 5200MHz' },
    { label: 'Almacenamiento', value: '2TB NVMe' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-6': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'Servidor Xeon Quadro' },
    { label: 'Procesador', value: 'Intel Xeon W-2295' },
    { label: 'RAM', value: '128GB DDR4 ECC' },
    { label: 'Almacenamiento', value: '8TB RAID SSD' },
    { label: 'Sistema operativo', value: 'Windows Server 2022' },
    { label: 'Garantía', value: '24 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-7': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'PC Retro 80s Gaming' },
    { label: 'Procesador', value: 'AMD Ryzen 5 7600X' },
    { label: 'RAM', value: '16GB DDR5' },
    { label: 'Almacenamiento', value: '1TB SSD' },
    { label: 'Sistema operativo', value: 'Windows 11 Home' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'pc-8': [
    { label: 'Marca', value: 'JBimports Custom' },
    { label: 'Modelo', value: 'Budget i3' },
    { label: 'Procesador', value: 'Intel Core i3-13100' },
    { label: 'RAM', value: '8GB DDR4' },
    { label: 'Almacenamiento', value: '500GB SSD' },
    { label: 'Sistema operativo', value: 'Windows 11 Home' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // PLACAS DE VIDEO
  // ─────────────────────────────────────────
  'gpu-1': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 4090 Founders Edition' },
    { label: 'Memoria VRAM', value: '24GB GDDR6X' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'Resolución máxima', value: '7680x4320 (8K)' },
    { label: 'Puertos', value: '3x DisplayPort 1.4a, 1x HDMI 2.1' },
    { label: 'TDP', value: '450W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-2': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 4070 Ti Gaming' },
    { label: 'Memoria VRAM', value: '12GB GDDR6X' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'Resolución máxima', value: '7680x4320 (8K)' },
    { label: 'Puertos', value: '3x DisplayPort 1.4a, 1x HDMI 2.1' },
    { label: 'TDP', value: '285W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-3': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 4070 Super' },
    { label: 'Memoria VRAM', value: '12GB GDDR6X' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'Resolución máxima', value: '7680x4320 (8K)' },
    { label: 'TDP', value: '220W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-4': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 4060 Ti' },
    { label: 'Memoria VRAM', value: '8GB GDDR6' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'TDP', value: '165W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-5': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 4060' },
    { label: 'Memoria VRAM', value: '8GB GDDR6' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'TDP', value: '115W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-6': [
    { label: 'Marca', value: 'NVIDIA' },
    { label: 'Modelo', value: 'RTX 3090 Ti' },
    { label: 'Memoria VRAM', value: '24GB GDDR6X' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'TDP', value: '450W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-7': [
    { label: 'Marca', value: 'AMD' },
    { label: 'Modelo', value: 'Radeon RX 7900 XTX' },
    { label: 'Memoria VRAM', value: '24GB GDDR6' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'Puertos', value: '2x DisplayPort 2.1, 1x HDMI 2.1, 1x USB-C' },
    { label: 'TDP', value: '355W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'gpu-8': [
    { label: 'Marca', value: 'AMD' },
    { label: 'Modelo', value: 'Radeon RX 7700 XT' },
    { label: 'Memoria VRAM', value: '12GB GDDR6' },
    { label: 'Interfaz', value: 'PCIe 4.0 x16' },
    { label: 'TDP', value: '245W' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // MONITORES
  // ─────────────────────────────────────────
  'mon-1': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '27"' },
    { label: 'Resolución', value: '3840x2160 (4K UHD)' },
    { label: 'Frecuencia de refresco', value: '144Hz' },
    { label: 'Tipo de panel', value: 'IPS' },
    { label: 'Conectividad', value: '2x HDMI 2.1, 2x DisplayPort 1.4' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-2': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '27"' },
    { label: 'Resolución', value: '2560x1440 (1440p)' },
    { label: 'Frecuencia de refresco', value: '240Hz' },
    { label: 'Tipo de panel', value: 'IPS' },
    { label: 'Tiempo de respuesta (ms)', value: '1ms GTG' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-3': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '34"' },
    { label: 'Resolución', value: '3440x1440 (UWQHD)' },
    { label: 'Frecuencia de refresco', value: '100Hz' },
    { label: 'Tipo de panel', value: 'VA Curvo' },
    { label: 'Conectividad', value: '1x HDMI 2.0, 2x DisplayPort 1.4' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-4': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '24"' },
    { label: 'Resolución', value: '1920x1080 (Full HD)' },
    { label: 'Frecuencia de refresco', value: '60Hz' },
    { label: 'Tipo de panel', value: 'TN' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-5': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '24"' },
    { label: 'Resolución', value: '1920x1080 (Full HD)' },
    { label: 'Frecuencia de refresco', value: '165Hz' },
    { label: 'Tipo de panel', value: 'IPS' },
    { label: 'Tiempo de respuesta (ms)', value: '1ms' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-6': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '32"' },
    { label: 'Resolución', value: '3840x2160 (4K UHD)' },
    { label: 'Frecuencia de refresco', value: '120Hz' },
    { label: 'Tipo de panel', value: 'OLED' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-7': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '27"' },
    { label: 'Resolución', value: '2560x1440 (1440p)' },
    { label: 'Frecuencia de refresco', value: '144Hz' },
    { label: 'Tipo de panel', value: 'VA Curvo' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mon-8': [
    { label: 'Marca', value: 'Generic' },
    { label: 'Tamaño', value: '15.6"' },
    { label: 'Resolución', value: '1920x1080 (Full HD)' },
    { label: 'Conectividad', value: 'USB-C, Mini HDMI' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // NOTEBOOKS
  // ─────────────────────────────────────────
  'nb-1': [
    { label: 'Marca', value: 'Apple' },
    { label: 'Modelo', value: 'MacBook Pro 16" M3 Max' },
    { label: 'Procesador', value: 'Apple M3 Max (16 núcleos)' },
    { label: 'RAM', value: '36GB Unified Memory' },
    { label: 'Almacenamiento', value: '1TB SSD' },
    { label: 'Pantalla', value: '16.2" Liquid Retina XDR' },
    { label: 'Sistema operativo', value: 'macOS Sonoma' },
    { label: 'Autonomía', value: 'Hasta 22 horas' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'nb-2': [
    { label: 'Marca', value: 'Dell' },
    { label: 'Modelo', value: 'XPS 15 i7 RTX 4070' },
    { label: 'Procesador', value: 'Intel Core i7-13700H' },
    { label: 'Tarjeta de video', value: 'NVIDIA RTX 4070' },
    { label: 'RAM', value: '32GB DDR5' },
    { label: 'Almacenamiento', value: '1TB SSD NVMe' },
    { label: 'Pantalla', value: '15.6" OLED 3.5K 120Hz' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'nb-3': [
    { label: 'Marca', value: 'ASUS' },
    { label: 'Modelo', value: 'ROG Zephyrus M16' },
    { label: 'Procesador', value: 'Intel Core i9-13900H' },
    { label: 'Tarjeta de video', value: 'NVIDIA RTX 4080 Laptop' },
    { label: 'RAM', value: '32GB DDR5' },
    { label: 'Almacenamiento', value: '2TB SSD NVMe' },
    { label: 'Pantalla', value: '16" QHD 240Hz IPS' },
    { label: 'Sistema operativo', value: 'Windows 11 Home' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'nb-4': [
    { label: 'Marca', value: 'Lenovo' },
    { label: 'Modelo', value: 'ThinkPad X1 Carbon Gen 11' },
    { label: 'Procesador', value: 'Intel Core i7-1365U' },
    { label: 'RAM', value: '16GB LPDDR5' },
    { label: 'Almacenamiento', value: '512GB SSD' },
    { label: 'Pantalla', value: '14" 2.8K OLED 120Hz' },
    { label: 'Sistema operativo', value: 'Windows 11 Pro' },
    { label: 'Autonomía', value: 'Hasta 15 horas' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'nb-5': [
    { label: 'Marca', value: 'HP' },
    { label: 'Modelo', value: 'Pavilion 15 i5 8GB' },
    { label: 'Procesador', value: 'Intel Core i5-1335U' },
    { label: 'RAM', value: '8GB DDR4' },
    { label: 'Almacenamiento', value: '512GB SSD' },
    { label: 'Pantalla', value: '15.6" FHD 250nits' },
    { label: 'Sistema operativo', value: 'Windows 11 Home' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // MEMORIAS RAM
  // ─────────────────────────────────────────
  'ram-1': [
    { label: 'Marca', value: 'Corsair' },
    { label: 'Modelo', value: 'Dominator Platinum RGB' },
    { label: 'Tipo', value: 'DDR5' },
    { label: 'Capacidad', value: '32GB (2x16GB)' },
    { label: 'Velocidad', value: '6000MHz' },
    { label: 'Latencia', value: 'CL36' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ram-2': [
    { label: 'Marca', value: 'G.Skill' },
    { label: 'Modelo', value: 'Trident Z5 RGB' },
    { label: 'Tipo', value: 'DDR5' },
    { label: 'Capacidad', value: '32GB (2x16GB)' },
    { label: 'Velocidad', value: '6000MHz' },
    { label: 'Latencia', value: 'CL30' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ram-3': [
    { label: 'Marca', value: 'Kingston' },
    { label: 'Modelo', value: 'HyperX Fury' },
    { label: 'Tipo', value: 'DDR4' },
    { label: 'Capacidad', value: '16GB (2x8GB)' },
    { label: 'Velocidad', value: '3200MHz' },
    { label: 'Latencia', value: 'CL16' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ram-4': [
    { label: 'Marca', value: 'Crucial' },
    { label: 'Modelo', value: 'Ballistix RGB' },
    { label: 'Tipo', value: 'DDR4' },
    { label: 'Capacidad', value: '32GB (2x16GB)' },
    { label: 'Velocidad', value: '3600MHz' },
    { label: 'Latencia', value: 'CL16' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ram-5': [
    { label: 'Marca', value: 'ADATA' },
    { label: 'Modelo', value: 'XPG Spectrix D60G' },
    { label: 'Tipo', value: 'DDR5' },
    { label: 'Capacidad', value: '32GB (2x16GB)' },
    { label: 'Velocidad', value: '6000MHz' },
    { label: 'Latencia', value: 'CL40' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // MOTHERS
  // ─────────────────────────────────────────
  'mb-1': [
    { label: 'Marca', value: 'ASUS' },
    { label: 'Modelo', value: 'ROG Maximus Z890 Hero' },
    { label: 'Socket', value: 'Intel LGA1851' },
    { label: 'Factor de forma', value: 'ATX' },
    { label: 'Soporte de RAM', value: '4x DDR5 hasta 192GB' },
    { label: 'Almacenamiento', value: '5x M.2, 6x SATA 6Gb/s' },
    { label: 'Red', value: '10GbE LAN + WiFi 7' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mb-2': [
    { label: 'Marca', value: 'MSI' },
    { label: 'Modelo', value: 'MPG B870E Carbon WiFi' },
    { label: 'Socket', value: 'AMD AM5' },
    { label: 'Factor de forma', value: 'ATX' },
    { label: 'Soporte de RAM', value: '4x DDR5 hasta 256GB' },
    { label: 'Almacenamiento', value: '4x M.2, 6x SATA 6Gb/s' },
    { label: 'Red', value: '2.5GbE LAN + WiFi 6E' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mb-3': [
    { label: 'Marca', value: 'GIGABYTE' },
    { label: 'Modelo', value: 'B850 Aorus Master' },
    { label: 'Socket', value: 'AMD AM5' },
    { label: 'Factor de forma', value: 'ATX' },
    { label: 'Soporte de RAM', value: '4x DDR5 hasta 256GB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'mb-4': [
    { label: 'Marca', value: 'ASRock' },
    { label: 'Modelo', value: 'B870M Phantom Gaming WiFi' },
    { label: 'Socket', value: 'AMD AM5' },
    { label: 'Factor de forma', value: 'Micro-ATX' },
    { label: 'Soporte de RAM', value: '2x DDR5 hasta 96GB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // GABINETES
  // ─────────────────────────────────────────
  'cab-1': [
    { label: 'Marca', value: 'NZXT' },
    { label: 'Modelo', value: 'H7 Flow RGB' },
    { label: 'Factor de forma compatible', value: 'ATX, Micro-ATX, Mini-ITX' },
    { label: 'Ventiladores incluidos', value: '3x 120mm RGB' },
    { label: 'Soporte de radiador', value: 'Hasta 360mm' },
    { label: 'Ventana lateral', value: 'Vidrio templado' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'cab-2': [
    { label: 'Marca', value: 'Corsair' },
    { label: 'Modelo', value: '5000T Airflow RGB' },
    { label: 'Factor de forma compatible', value: 'E-ATX, ATX, Micro-ATX, Mini-ITX' },
    { label: 'Ventiladores incluidos', value: '4x 120mm RGB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'cab-3': [
    { label: 'Marca', value: 'Lian Li' },
    { label: 'Modelo', value: 'LANCOOL 215' },
    { label: 'Factor de forma compatible', value: 'ATX, Micro-ATX, Mini-ITX' },
    { label: 'Ventiladores incluidos', value: '2x 140mm ARGB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'cab-4': [
    { label: 'Marca', value: 'Fractal Design' },
    { label: 'Modelo', value: 'Core 1000 USB 3.0' },
    { label: 'Factor de forma compatible', value: 'Micro-ATX, Mini-ITX' },
    { label: 'Ventiladores incluidos', value: '1x 120mm' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // FUENTES
  // ─────────────────────────────────────────
  'psu-1': [
    { label: 'Marca', value: 'Corsair' },
    { label: 'Modelo', value: 'RM1200x' },
    { label: 'Potencia', value: '1200W' },
    { label: 'Certificación', value: '80 Plus Gold' },
    { label: 'Modularidad', value: 'Totalmente modular' },
    { label: 'Garantía', value: '10 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'psu-2': [
    { label: 'Marca', value: 'EVGA' },
    { label: 'Modelo', value: 'SuperNOVA G6 850W' },
    { label: 'Potencia', value: '850W' },
    { label: 'Certificación', value: '80 Plus Gold' },
    { label: 'Modularidad', value: 'Totalmente modular' },
    { label: 'Garantía', value: '10 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'psu-3': [
    { label: 'Marca', value: 'Seasonic' },
    { label: 'Modelo', value: 'FOCUS GX-750' },
    { label: 'Potencia', value: '750W' },
    { label: 'Certificación', value: '80 Plus Gold' },
    { label: 'Modularidad', value: 'Totalmente modular' },
    { label: 'Garantía', value: '10 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'psu-4': [
    { label: 'Marca', value: 'Thermaltake' },
    { label: 'Modelo', value: 'Toughpower GF1 650W' },
    { label: 'Potencia', value: '650W' },
    { label: 'Certificación', value: '80 Plus Gold' },
    { label: 'Modularidad', value: 'Semi-modular' },
    { label: 'Garantía', value: '10 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // PERIFÉRICOS
  // ─────────────────────────────────────────
  'per-1': [
    { label: 'Marca', value: 'Logitech' },
    { label: 'Modelo', value: 'MX Master 3S' },
    { label: 'Tipo', value: 'Mouse inalámbrico' },
    { label: 'Conectividad', value: 'Bluetooth + USB Nano Receiver' },
    { label: 'DPI', value: 'Hasta 8000 DPI' },
    { label: 'Autonomía', value: 'Hasta 70 días' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'per-2': [
    { label: 'Marca', value: 'Corsair' },
    { label: 'Modelo', value: 'K95 RGB Platinum XT' },
    { label: 'Tipo', value: 'Teclado mecánico gaming' },
    { label: 'Switch', value: 'Cherry MX Speed' },
    { label: 'Conectividad', value: 'USB con cable' },
    { label: 'Retroiluminación', value: 'RGB per-key' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'per-3': [
    { label: 'Marca', value: 'SteelSeries' },
    { label: 'Modelo', value: 'Arctis Nova Pro Wireless' },
    { label: 'Tipo', value: 'Headset gaming inalámbrico' },
    { label: 'Respuesta en frecuencia', value: '10Hz – 40.000Hz' },
    { label: 'Autonomía', value: 'Hasta 44 horas' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'per-4': [
    { label: 'Marca', value: 'Razer' },
    { label: 'Modelo', value: 'DeathAdder V3' },
    { label: 'Tipo', value: 'Mouse gaming con cable' },
    { label: 'DPI', value: 'Hasta 30.000 DPI' },
    { label: 'Sensor', value: 'Razer Focus Pro 30K' },
    { label: 'Peso', value: '59g' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // ALMACENAMIENTO
  // ─────────────────────────────────────────
  'ssd-1': [
    { label: 'Marca', value: 'Samsung' },
    { label: 'Modelo', value: '990 Pro' },
    { label: 'Capacidad', value: '2TB' },
    { label: 'Interfaz', value: 'M.2 PCIe 4.0 x4 NVMe' },
    { label: 'Lectura secuencial', value: '7.450 MB/s' },
    { label: 'Escritura secuencial', value: '6.900 MB/s' },
    { label: 'Garantía', value: '5 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ssd-2': [
    { label: 'Marca', value: 'Western Digital' },
    { label: 'Modelo', value: 'Black SN850X' },
    { label: 'Capacidad', value: '1TB' },
    { label: 'Interfaz', value: 'M.2 PCIe 4.0 x4 NVMe' },
    { label: 'Lectura secuencial', value: '7.300 MB/s' },
    { label: 'Escritura secuencial', value: '6.600 MB/s' },
    { label: 'Garantía', value: '5 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ssd-3': [
    { label: 'Marca', value: 'Crucial' },
    { label: 'Modelo', value: 'MX500' },
    { label: 'Capacidad', value: '2TB' },
    { label: 'Interfaz', value: 'SATA III 6Gb/s' },
    { label: 'Lectura secuencial', value: '560 MB/s' },
    { label: 'Escritura secuencial', value: '510 MB/s' },
    { label: 'Garantía', value: '5 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'ssd-4': [
    { label: 'Marca', value: 'Kingston' },
    { label: 'Modelo', value: 'A2000' },
    { label: 'Capacidad', value: '1TB' },
    { label: 'Interfaz', value: 'M.2 PCIe 3.0 x4 NVMe' },
    { label: 'Lectura secuencial', value: '2.200 MB/s' },
    { label: 'Escritura secuencial', value: '2.000 MB/s' },
    { label: 'Garantía', value: '5 años' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],

  // ─────────────────────────────────────────
  // IMPRESORAS
  // ─────────────────────────────────────────
  'imp-1': [
    { label: 'Marca', value: 'HP' },
    { label: 'Modelo', value: 'LaserJet Pro M404n' },
    { label: 'Tipo', value: 'Láser monocromático' },
    { label: 'Velocidad', value: '38 ppm' },
    { label: 'Conectividad', value: 'Ethernet, USB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'imp-2': [
    { label: 'Marca', value: 'Canon' },
    { label: 'Modelo', value: 'imagePRESS C165' },
    { label: 'Tipo', value: 'Láser color' },
    { label: 'Velocidad', value: '65 ppm color' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'imp-3': [
    { label: 'Marca', value: 'Xerox' },
    { label: 'Modelo', value: 'VersaLink C415' },
    { label: 'Tipo', value: 'Multifunción láser color' },
    { label: 'Funciones', value: 'Imprime, escanea, copia, fax' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
  'imp-4': [
    { label: 'Marca', value: 'Epson' },
    { label: 'Modelo', value: 'WorkForce Pro WF-4830' },
    { label: 'Tipo', value: 'Inyección de tinta' },
    { label: 'Velocidad', value: '25 ppm negro, 12 ppm color' },
    { label: 'Conectividad', value: 'WiFi, Ethernet, USB' },
    { label: 'Garantía', value: '12 meses' },
    { label: 'Condición', value: 'Nuevo, en caja sellada' },
  ],
};

/**
 * Retorna las especificaciones de un producto por ID.
 * Si no existen specs definidas, devuelve un array vacío.
 */
export function getSpecsByProductId(productId: string): Spec[] {
  return productSpecifications[productId] ?? [];
}
